# Generated by Django 5.2.9 on 2025-12-08 04:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="consultation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={},
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="content",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="consultation",
            old_name="is_completed",
            new_name="is_paid",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="content",
            new_name="question",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="author",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="consultation_type",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="description",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="duration_hours",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="expert",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="farmer",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="location",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="meeting_link",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="mpesa_receipt_number",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="mpesa_transaction_id",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="scheduled_date",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="expertise",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="farmer_profile",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="hourly_rate",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="years_experience",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="receipt_number",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="question",
            name="author",
        ),
        migrations.RemoveField(
            model_name="question",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="question",
            name="is_solved",
        ),
        migrations.RemoveField(
            model_name="question",
            name="title",
        ),
        migrations.RemoveField(
            model_name="question",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="question",
            name="views",
        ),
        migrations.AddField(
            model_name="answer",
            name="expert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answers",
                to="consultations.expert",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="amount_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="mpesa_receipt",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="phone",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.question",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultation",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expert",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="expert",
            name="specialization",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="expert",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="callback_body",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="checkout_request_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="mpesa_receipt",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expert",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="expert",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="expert",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expert_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="consultations.consultation",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ConsultationBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("online", "Online Consultation"),
                            ("office", "Office Visit"),
                            ("farm", "Farm Visit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("preferred_date", models.DateField()),
                ("amount", models.IntegerField(default=0)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "mpesa_receipt",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
