# Generated by Django 5.2.9 on 2025-12-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0002_alter_answer_options_alter_consultation_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="consultations.consultationbooking",
            ),
        ),
    ]
