# Generated by Django 5.2.9 on 2025-12-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0003_alter_paymenttransaction_consultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="consultations.expert",
            ),
        ),
    ]
